### ISSUE TITLE
Require "xlrd" or "xlrd-parser"?

### ISSUE THREAD

**Issue by selfinterest** [extrabacon/xlrd-parser#1]
First off, I really like this project, so thank you for doing it!

Second, the sample project and the online documentation requires "xlrd", but my application can't find the module unless I require "xlrd-parser." Is that the way it is supposed to work?

Thanks!

**Comment by extrabacon** [comment]
Sorry about that. This project started off as a separate module named "xlrd", but I changed the name to "xlrd-parser" later when I published it to NPM. So I fixed the README file as well as the sample.

BTW if you are interested in this project, take a look at https://github.com/extrabacon/pyspreadsheet, which is essentially the successor to xlrd-parser. Pyspreadsheet integrates with more open-source libraries in order to add write support! It is definitely not production-ready, but it should be soon since it is part of another project I am working on.
